---
engines:
  duplication:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
      complexity:
        enabled: true
      standard/object-curly-even-spacing:
        enabled: false
      standard/array-bracket-even-spacing:
        enabled: false
      standard/computed-property-even-spacing:
        enabled: false
      promise/param-names:
        enabled: false
      standard/array-bracket-even-spacing:
        enabled: false
      standard/computed-property-even-spacing:
          enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
  - "/__tests__/*"
  - "/node_modules/*"
