---
engines:
  duplication:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
      complexity:
        enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
  - "/__tests__/*"
  - "/node_modules/*"
