environment:
  NOVE_ENV: production #Changes behavior of npm install / yarn install
  CODECLIMATE_REPO_TOKEN: a2e1de6b086b7499a462b1aaec6b39d6369c74ea33232dc9885db3fb1f23527d
  matrix:
    - nodejs_version: '6'
matrix:
  fast_finish: true
build: off
clone_depth: 1
skip_tags: true
skip_branch_with_pr: true
shallow_clone: true
branches:
  except:
    - gh-pages
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install --global npm standard snazzy flow-bin
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
before_test:
  - npm version
test_script:
  - npm test
after_test:
  - npm run lint-check
  - cmd: appveyor-retry powershell npm run flow-check
