environment:
  NOVE_ENV: production #Changes behavior of npm install / yarn install
  matrix:
    - nodejs_version: '6'
matrix:
  fast_finish: true
build: off
clone_depth: 1
skip_tags: true
skip_branch_with_pr: true
shallow_clone: true
branches:
  except:
    - gh-pages
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install --global npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
before_test:
  - npm version
  - npm run lint-check
  - cmd: appveyor-retry powershell npm run flow-check
test_script:
  - npm test
