environment:
  NOVE_ENV: production #Changes behavior of npm install / yarn install
  CODECLIMATE_REPO_TOKEN: 9a8d999dfebca03e28a1c2263cf3b2572f59f894a35a96cb379f01616e47b3e1
  matrix:
    - nodejs_version: '6'
matrix:
  fast_finish: true
build: off
clone_depth: 1
skip_tags: true
skip_branch_with_pr: true
shallow_clone: true
branches:
  except:
    - gh-pages
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install --global npm standard snazzy flow-bin
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
before_test:
  - npm version
test_script:
#  - npm test
# We are having issues due RealmJS is not compatible with windows environment
after_test:
  - npm run lint-check
  - cmd: appveyor-retry powershell npm run flow-check
