// flow-typed signature: 95cf01230aedcd9c3001176f4099f28d
// flow-typed version: <<STUB>>/react-native-ui-kitten_v^0.0.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-ui-kitten'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-ui-kitten' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-ui-kitten/components/boardup/BoardUpView' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/button/Button' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/card/Card' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/choice/Choice' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/choice/ChoiceGroup' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/image/ModalImg' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/separator/Separator' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/status/BarBg' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/tab/Tab' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/tab/TabView' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/text/Text' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/components/textinput/TextInput' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/color' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/component-styles/button' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/component-styles/card' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/component-styles/choice' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/component-styles/index' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/component-styles/tab' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/component-styles/textinput' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/config' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/style' {
  declare module.exports: any;
}

declare module 'react-native-ui-kitten/util/themes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-ui-kitten/components/boardup/BoardUpView.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/boardup/BoardUpView'>;
}
declare module 'react-native-ui-kitten/components/button/Button.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/button/Button'>;
}
declare module 'react-native-ui-kitten/components/card/Card.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/card/Card'>;
}
declare module 'react-native-ui-kitten/components/choice/Choice.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/choice/Choice'>;
}
declare module 'react-native-ui-kitten/components/choice/ChoiceGroup.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/choice/ChoiceGroup'>;
}
declare module 'react-native-ui-kitten/components/image/ModalImg.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/image/ModalImg'>;
}
declare module 'react-native-ui-kitten/components/separator/Separator.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/separator/Separator'>;
}
declare module 'react-native-ui-kitten/components/status/BarBg.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/status/BarBg'>;
}
declare module 'react-native-ui-kitten/components/tab/Tab.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/tab/Tab'>;
}
declare module 'react-native-ui-kitten/components/tab/TabView.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/tab/TabView'>;
}
declare module 'react-native-ui-kitten/components/text/Text.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/text/Text'>;
}
declare module 'react-native-ui-kitten/components/textinput/TextInput.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/components/textinput/TextInput'>;
}
declare module 'react-native-ui-kitten/index' {
  declare module.exports: $Exports<'react-native-ui-kitten'>;
}
declare module 'react-native-ui-kitten/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten'>;
}
declare module 'react-native-ui-kitten/util/color.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/color'>;
}
declare module 'react-native-ui-kitten/util/component-styles/button.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/component-styles/button'>;
}
declare module 'react-native-ui-kitten/util/component-styles/card.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/component-styles/card'>;
}
declare module 'react-native-ui-kitten/util/component-styles/choice.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/component-styles/choice'>;
}
declare module 'react-native-ui-kitten/util/component-styles/index.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/component-styles/index'>;
}
declare module 'react-native-ui-kitten/util/component-styles/tab.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/component-styles/tab'>;
}
declare module 'react-native-ui-kitten/util/component-styles/textinput.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/component-styles/textinput'>;
}
declare module 'react-native-ui-kitten/util/config.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/config'>;
}
declare module 'react-native-ui-kitten/util/style.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/style'>;
}
declare module 'react-native-ui-kitten/util/themes.js' {
  declare module.exports: $Exports<'react-native-ui-kitten/util/themes'>;
}
